### ISSUE TITLE
how to used ?

### ISSUE THREAD

**Issue by jasonz1987** [bernhard-42/three-cad-viewer#12]
i have a stp model file ,how to used your project to load the stp file ?

**Comment by bernhard-42** [comment]
This is just the viewer component. It is integrated into [OCP CAD VIEWER](https://github.com/bernhard-42/vscode-ocp-cad-viewer) and you can use [CadQuery](https://github.com/CadQuery/cadquery) or [build123d](https://github.com/gumyr/build123d) to import the step file with Python and then visualize it
