### ISSUE TITLE
How to add image texture to the generated model

### ISSUE THREAD

**Issue by RustLoverTheCoder** [bernhard-42/three-cad-viewer#20]
I changed the texture in parts, but the model didn't show the image
![image](https://github.com/user-attachments/assets/ce675efb-f077-4852-971d-829e0dc55d3f)

**Comment by bernhard-42** [comment]
The viewer component is built for the specific use cases of  [vscode-ocp-cad-viewer](https://github.com/bernhard-42/vscode-ocp-cad-viewer).
As such it only supports what I need there :-)

Textures are only supported on faces (subtype `face`) and not on solids.
Example: https://github.com/bernhard-42/three-cad-viewer/blob/master/examples/image-face.js
