### ISSUE TITLE
provide default up option

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/three-cad-viewer#7]
The new release introduced a new bug with error `cameraUp[this.up] is undefined`, coming from `this.pCamera.up.set(...cameraUp[this.up]);` [in camera.js](https://github.com/bernhard-42/three-cad-viewer/blob/master/src/camera.js#L76) (probably introduced in af2cfc869f0b851f4db524ecc34e5c3f82a7e112).

I had to manually set `options.up = 'Z'` to fix this, but I think a default value should be set.

**Comment by bernhard-42** [comment]
Agreed, I had always set up in my tests.
I understand you are not blocked, right?

**Comment by roipoussiere** [comment]
Yes I defaulted to Z, you have time: https://github.com/roipoussiere/cadquery-server/commit/1ace68a45261e43900f202540c761ae4889d5741
