### ISSUE TITLE
Items in More dropdown menu might be truncated

### ISSUE THREAD

**Issue by roipoussiere** [bernhard-42/three-cad-viewer#8]
This appens when the window width roughly fits the toolbar width:

![image](https://user-images.githubusercontent.com/1665542/191744535-2eaf37f1-b209-48d7-a35a-e566e072b205.png)

I think it could be fixed if the menu is aligned to the right of the More button.

**Comment by bernhard-42** [comment]
Aligning to the right will make the dropdown overlap with the orientation buttons. Looks pretty ugly.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/954408/192048341-6ad0ea48-c080-48b8-bcfd-b44e891a033d.png">

I would recommend to set a minimum width. In glass mode 685px works pretty well.

**Comment by bernhard-42** [comment]
Closing, won't fix
