### ISSUE TITLE
More Advanced ThreeJS Materials

### ISSUE THREAD

**Issue by jdegenstein** [bernhard-42/three-cad-viewer#9]
ThreeJS supports MeshPhysicalMaterial, which could enhance the appearance of models displayed in three-cad-viewer.

![image](https://user-images.githubusercontent.com/16868537/234407931-71244e09-5009-4619-8982-9ce67e29d7f0.png)

Here's an example configuration with a semi-metallic, semi-reflective material. This can be reproduced at this link:

https://threejs.org/docs/scenes/material-browser.html#MeshPhysicalMaterial

**Comment by bernhard-42** [comment]
Fixed in 1.8.2

**Comment by bernhard-42** [comment]
closing
